---
- name: Converge
  hosts: all
  roles:
    - role: ansible-react
      vars:
        react_system_user: "react"
        react_system_group: "www-data"
        react_system_user_home: "/home/{{ react_system_user }}"
        react_node_version: 10.x
        react_git_url: "https://github.com/OpenSRP/web.git"
        react_git_version: "master"
        react_app_settings:
          GENERATE_SOURCEMAP: "false"
          SKIP_PREFLIGHT_CHECK: "true"
        react_remote_js_build: false
        react_local_app_path: "{{ react_local_checkout_path }}/app"
        react_app_path: "{{ react_checkout_path }}/app"
        react_build_cmds:
          - cmd: lerna:prepublish
            args: --scope @opensrp/store
          - cmd: lerna:prepublish
          - cmd: build
